app:
  name: 'sd'
  version: '1.0.0'

http:
  port: '8082'
  cookie_store_key: 'NpEPi8pEjKVjLGJ6kYCS+VTCzi6BUuDzU0wrwXyf5uDPArtlofn2AG6aTMiPmN3C909rsEWMNqJqhIVPGP3Exg=='
  session_store_key: 'AbfYwmmt8UCwUuhd9qvfNA9UCuN1cVcKJN1ofbiky6xCyyBj20whe40rJa3Su0WOWLWcPpO1taqJdsEI/65+JA=='

logger:
  log_format: "json"
  log_level: "info"
  log_no_color: true

postgres:
  pool_max: 2
