// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/MatthewBehnke/apis/pkg/database/ent/runtime.go

const (
	Version = "v0.11.5-0.20221212200803-3328201ba8a9"           // Version of ent codegen.
	Sum     = "h1:cbHpH6nLmNvMwEcVCiTm5+stuExtwbdUpEW1gdkfEFY=" // Sum of ent codegen.
)
